// System-managed sync layer.
//
// - Mirror CLAUDE.md ↔ AGENTS.md inside every department folder.
// - Copy root org.md into every department.
// - Regenerate _org.md (list of departments + one-line summaries) per folder.
// - Sync skills/ into provider-specific destinations (v1: copies into .claude/skills
//   and .codex/skills under each department, so both providers discover them).
//
// Commits as "aios: sync" so system-generated churn is separable from operator edits.

import { readFile, writeFile, stat, mkdir, copyFile, readdir } from "fs/promises";
import { existsSync } from "fs";
import { join } from "path";

import { config } from "../config";
import { listDepartments } from "./departments";
import { gitRun } from "./repo";
import { log } from "../log";
import { sendNotification } from "./notifications";

async function writeIfChanged(path: string, content: string): Promise<boolean> {
  try {
    const prev = await readFile(path, "utf-8");
    if (prev === content) return false;
  } catch {}
  await mkdir(require("path").dirname(path), { recursive: true });
  await writeFile(path, content, "utf-8");
  return true;
}

async function readFirstLineDescription(contextPath: string): Promise<string> {
  try {
    const raw = await readFile(contextPath, "utf-8");
    const lines = raw.split(/\r?\n/);
    for (const ln of lines) {
      const cleaned = ln.replace(/^#+\s*/, "").trim();
      if (cleaned) return cleaned.slice(0, 200);
    }
  } catch {}
  return "(no CLAUDE.md)";
}

async function copyTree(src: string, dst: string): Promise<void> {
  if (!existsSync(src)) return;
  const s = await stat(src);
  if (s.isDirectory()) {
    await mkdir(dst, { recursive: true });
    const entries = await readdir(src);
    for (const e of entries) await copyTree(join(src, e), join(dst, e));
  } else {
    await mkdir(require("path").dirname(dst), { recursive: true });
    await copyFile(src, dst);
  }
}

export interface SyncResult {
  changed: string[];
  conflicts: Array<{ path: string; message: string }>;
}

export async function runSyncLayer(opts: { commit?: boolean } = { commit: true }): Promise<SyncResult> {
  const out: SyncResult = { changed: [], conflicts: [] };
  const depts = await listDepartments();

  // 1. CLAUDE.md ↔ AGENTS.md per department (and at repo root).
  await mirrorClaudeAgents(config.repoDir, out);
  for (const d of depts) await mirrorClaudeAgents(d.path, out);

  // 2. org.md propagation.
  const rootOrg = join(config.repoDir, "org.md");
  if (existsSync(rootOrg)) {
    const orgBody = await readFile(rootOrg, "utf-8");
    for (const d of depts) {
      const dst = join(d.path, "org.md");
      if (await writeIfChanged(dst, orgBody)) out.changed.push(dst);
    }
  }

  // 3. _org.md per department.
  const summaries: Array<{ name: string; line: string }> = [];
  for (const d of depts) summaries.push({ name: d.name, line: await readFirstLineDescription(d.contextPath) });
  const orgMapLines = [
    "# Organization map (auto-generated by AIOS; do not edit by hand)",
    "",
    ...summaries.map((s) => `- **${s.name}**: ${s.line}`),
    "",
  ];
  const orgMap = orgMapLines.join("\n");
  for (const d of depts) {
    const dst = join(d.path, "_org.md");
    if (await writeIfChanged(dst, orgMap)) out.changed.push(dst);
  }

  // 4. Skills sync. Canonical location: <dept>/skills/. Mirror into
  //    <dept>/.claude/skills/ and <dept>/.codex/skills/ so both providers see them.
  for (const d of depts) {
    const canonical = join(d.path, "skills");
    if (!existsSync(canonical)) continue;
    for (const target of [join(d.path, ".claude", "skills"), join(d.path, ".codex", "skills")]) {
      try {
        await mkdir(target, { recursive: true });
        await copyTree(canonical, target);
        out.changed.push(target);
      } catch (e: any) {
        out.conflicts.push({ path: target, message: String(e?.message || e) });
      }
    }
  }

  if (out.changed.length && opts.commit !== false) {
    try {
      await gitRun(["add", "-A"]);
      const { stdout: status } = await gitRun(["status", "--porcelain"]);
      if (status.trim()) {
        await gitRun(["commit", "-m", "aios: sync"]);
        await gitRun(["push", "origin", "HEAD"]).catch(() => {});
      }
    } catch (e: any) {
      log.warn("sync: commit/push failed", e?.message || e);
    }
  }

  if (out.conflicts.length) {
    const lines = out.conflicts.map((c) => `- ${c.path}: ${c.message}`).join("\n");
    await sendNotification(`AIOS sync detected conflicts and left files unchanged.\n${lines}`, "AIOS sync conflict")
      .catch(() => {});
  }

  return out;
}

async function mirrorClaudeAgents(dir: string, out: SyncResult) {
  const claude = join(dir, "CLAUDE.md");
  const agents = join(dir, "AGENTS.md");
  const hasClaude = existsSync(claude);
  const hasAgents = existsSync(agents);
  if (!hasClaude && !hasAgents) return;
  if (hasClaude && hasAgents) {
    const [a, b] = [await readFile(claude, "utf-8"), await readFile(agents, "utf-8")];
    if (a === b) return;
    out.conflicts.push({ path: dir, message: "divergent CLAUDE.md and AGENTS.md; resolve manually before sync can proceed" });
  } else if (hasClaude) {
    await copyFile(claude, agents);
    out.changed.push(agents);
  } else {
    await copyFile(agents, claude);
    out.changed.push(claude);
  }
}
